---
title: "06-23-21-Rt_dataset_tidy.Rmd"
author: "Eslam Abousamra"
date: "6/23/2021"
output: word_document
---

```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(lubridate)
library(modelr)
library(compare)
library(devtools)
library(openintro)
```



# Reading and sorting datasets
## Preparing Rt estimation dataset

## Reading and cleaning datasets to preparing for merging 


```{r}
cdc_raw = read.csv("cdc-data.csv")
covmeta_raw = read.csv("metadata-usa.csv")


#Dataset 1

init_df = covmeta_raw %>% select(date, division,pango_lineage)

#Standardizing date
init_df = init_df %>% mutate(
  date = as.Date(date, format("%m/%d/%y"))
)

view(init_df)


#Dataset 2

#Import and tidy data
cdc_mod = cdc_raw %>% select(submission_date, state, new_case)

#Rename variables
cdc_mod = cdc_mod %>% 
  rename(
    date = submission_date
  )
#converting state abbreviation to full name
cdc_mod = cdc_mod %>% mutate(newstate =
  abbr2state(state))
cdc_mod

#Renaming variables
cdc_mod = cdc_mod %>% select(date, newstate, new_case) %>%
  rename(
    division = newstate
  )
  
#Standardizing date
cdc_mod = cdc_mod %>% mutate(
  date = as.Date(date, format("%m/%d/%Y"))
)
view(cdc_mod)

```


# Merging two datasets 

## Addition of logistic regression fit data

```{r}
#Joining the two datasets
init_df_new= init_df %>% left_join(cdc_mod)


#tidying and prepping the dataset
init_df_new = init_df_new %>%
  count(date, pango_lineage,division)%>%
  group_by(date, division) %>%
  mutate(totalcount = sum(n))%>% 
  ungroup() %>% 
  mutate(freq = n/totalcount) %>%
  mutate(tlogit = qlogis(freq)) %>% 
  filter(is.finite(tlogit))

#Adding logistic regression fit data
init_df_new = init_df_new %>%
  
  nest(-division, -pango_lineage) %>% 
  
  mutate(fit1 = map(data, ~lm(tlogit ~ time(date), data = .)), 
         data = map2(.x = data, .y = fit1, ~add_predictions(.x, .y, var = "logit_pred"))) %>%
  
   unnest(data) %>%
  
  mutate(pred = plogis(logit_pred))


view(init_df_new)



```



















