---
title: "06-23-21-Rt_dataset_tidy.Rmd"
author: "Eslam Abousamra"
date: "6/23/2021"
output: word_document
---

```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(lubridate)
library(modelr)
library(compare)
library(devtools)
library(openintro)
library(EpiEstim)
library(data.table)

```



# Reading and sorting datasets
## Preparing Rt estimation dataset

## Reading and cleaning datasets to preparing for merging 


```{r}
cdc_raw = read.csv("cdc-data.csv")
covmeta_raw = read.csv("metadata-usa.csv")
```

```{r}
#Dataset 1

var_of_concern = c("B.1.1.7", "B.1.351", "P.1", "B.1.427", "B.1.617")


init_df = covmeta_raw %>% select(date, division,pango_lineage)

#Standardizing date
init_df = init_df %>% mutate(
  date = as.Date(date, format("%m/%d/%y"))
) %>% mutate(pango_lineage = case_when(pango_lineage %in% var_of_concern ~ pango_lineage, TRUE ~ "other"))

init_df


#Dataset 2

#Import and tidy data
cdc_mod = cdc_raw %>% select(submission_date, state, new_case)

#Rename variables
cdc_mod = cdc_mod %>% 
  rename(
    date = submission_date
  )
#converting state abbreviation to full name
cdc_mod = cdc_mod %>% mutate(newstate =
  abbr2state(state))
cdc_mod

#Renaming variables
cdc_mod = cdc_mod %>% select(date, newstate, new_case) %>%
  rename(
    division = newstate
  ) %>%
  filter(!is.na(division))
  
#Standardizing date
cdc_mod = cdc_mod %>% mutate(
  date = as.Date(date, format("%m/%d/%Y"))
) 

view(cdc_mod)

```


# Merging two datasets 

## Addition of multinomial logistic regression fit data

```{r}
#Joining the two datasets
init_df_new= init_df

init_df_new 

#tidying and prepping the dataset
init_df_new = init_df_new %>%
  count(date, pango_lineage, division)%>%
  group_by(date, division) %>%
  mutate(totalcount = sum(n))%>% 
  ungroup() %>% 
  mutate(freq = n/totalcount) 

  
  

# Wide dataset (resorting lineages) to pass in multinom reg model
init_df_new = init_df_new %>% 
  rename(sequences = n) %>%
  pivot_wider(names_from = pango_lineage, values_from = c(sequences, freq), values_fill = 0) 

init_df_new
```








```{r}
## Adding Mulitnomial Regression Fit

library(lubridate)
library(nnet)

#Create matrix tibble for states 

get_division_mat <- function(tbl){
  return(tbl %>%
  select(starts_with("sequences"), -totalcount) %>% # Get sequence counts
  rename_all(~str_replace(.,"^sequences","pred_freq")) %>% # Rename variable for later
  as.matrix())
}


get_division_times <- function(tbl){
  dt_mat <- tbl %>%
  select(date) %>%
  mutate(times = yday(date),
         times = (times - min(times)) / (max(times) - min(times))) # Transform times for easy fitting
  return(dt_mat$times)
}


init_df_new
#Fitting the multinomial frame

multinomial_frame <- init_df_new %>%
  nest(-division) %>%
# Nest by division
  mutate(division_mat = map(data, ~get_division_mat(.)), # Get counts 
         division_times = map(data, ~get_division_times(.)), # Get times
         model = map2(.x = division_mat, .y = division_times, ~multinom(.x ~ .y, trace = FALSE, MaxNWts = 100000)),predictions = map(model, ~ predict(., type = "prob")),  # Get predictions
         data = map2(.x = data, .y = predictions, ~ cbind(.x, .y))) %>% 
  # Augment original data with predictions
  select(division, data, model) %>%
  unnest(data)

multinomial_frame



```

# Reverting dataset to longer format

```{r}

multinomial_frame


#Converting seq.lineage to sequences
sequence_n <- multinomial_frame %>%
  select(division, date, totalcount, starts_with("sequences")) %>%
  pivot_longer(starts_with("sequences"), names_to = "pango_lineage", values_to = "sequence_n") %>%
  mutate(pango_lineage = str_replace(pango_lineage,"^sequences_",""))

#inverting the observed frequencies
obs_freqs <- multinomial_frame %>%
  select(division, date, totalcount, starts_with("freq")) %>%
  pivot_longer(starts_with("freq"), names_to = "pango_lineage", values_to = "obs_freq") %>%
  mutate(pango_lineage = str_replace(pango_lineage,"^freq_",""))

#Inverting the predicted frequencies
pred_freq <- multinomial_frame %>%
  select(division, date, totalcount, starts_with("pred_freq")) %>%
  pivot_longer(starts_with("pred_freq"), names_to = "pango_lineage", values_to = "pred_freq") %>%
  mutate(pango_lineage = str_replace(pango_lineage,"^pred_freq_",""))


multinomial_longer <- sequence_n %>% left_join(obs_freqs) %>% left_join(pred_freq)





multinomial_longer











```



# Joining the dataset
```{r}


final_mod = multinomial_longer %>% left_join(cdc_mod) 

#Estim predicted frequency for each lineage
final_mod = final_mod %>% mutate(pred_cases = pred_freq * new_case)



final_mod

write.csv(final_mod, "Rt_est_cdc&GISAID2.csv")

```



















