---
title: "07-12-21_CV_MLR"
author: "Eslam Abousamra"
date: "7/12/2021"
output: html_document
---

```{r}

library(dplyr)
library(ggplot2)
library(tidyverse)
library(lubridate)
library(lattice)
library(caret)
library(rpart)
library(Metrics)
library(Matrix)
library(caret)
library(lubridate)
library(nnet)
library(rsample)
library(ggrepel)

```

# Read Dataset and select relevant vars

```{r}
tidy_data = read.csv("Rt_MLR_cdc&GISAID.csv")%>%
  select(-X) %>% 
  mutate(date= as.Date(date)) %>%
  select(date, pango_lineage, division, n)
```

# Pre-processing
# Create training data, testing data
```{r}

#Create helper functions

#getting division matrix
get_division_mat <- function(tbl){
  return(tbl %>%
           select(-date, -times) %>% # Get sequence counts
           rename_all(~str_replace(.,"^sequences","pred_freq")) %>% # Rename variable for later
           as.matrix())
}

#getting division times
get_division_times <- function(tbl){
  dt_mat <- tbl %>%
    select(date) %>%
    mutate(times = yday(date),
           times = (times - min(times)) / (max(times) - min(times))) # Transform times for easy fitting
  return(dt_mat %>% select(times))
}


#Wide Dataset

tidy_wider = tidy_data %>%
  rename(sequences = n) %>%
  pivot_wider(names_from = pango_lineage, values_from = sequences, names_prefix= "sequences_", values_fill = 0) %>%
  nest(-division) %>% 
    mutate(data = map(.x = data, ~cbind(.x, get_division_times(.)))) %>%
  #splitting dataset > training, testing
  mutate(tt_split = map(data, ~ initial_time_split(., prop = 0.6)),
         train_data = map(tt_split, ~ training(.)),
         test_data = map(tt_split, ~ testing(.))) %>%
  mutate(division_mat_tr = map(train_data, ~get_division_mat(.))) %>% # Get counts for training data 
    mutate(division_mat_ts = map(test_data, ~get_division_mat(.)))

  
 


``` 


# Preprocessing data
### Create training, test, and validation sets


```{r}


## Fitting log multinomial regression to training data

train_mlr = tidy_wider %>%
  mutate(model_tr = map2(.x = division_mat_tr, .y = train_data, ~multinom(.x ~ times, data = .y, trace = FALSE, MaxNWts = 100000, model = TRUE)),
         predictions_tr = map(model_tr, ~ predict(., type = "prob")),# Get predictions
         data_tr = map2(.x = train_data, .y = predictions_tr, ~cbind(.x, .y)))

  
## predicting test data
test_mlr = train_mlr %>% 
  mutate(predictions_test = map2(.x = model_tr, .y = test_data,
                                 ~ predict(.x, type="probs", newdata= .y)),#Predict test by a trained set
         data_ts = map2(.x = test_data, .y = predictions_test, ~ cbind(.x, .y)))


```

# Sorting data for pivoting longer

```{r}


add_id = function(tbl, value){
  tbl %>% 
    add_column(id = value)
}


#adding IDs to training and test dataset 

final_data = test_mlr %>%
  select(division, data_tr, data_ts, model_tr) %>% mutate(
    data_tr = map(.x= data_tr, ~add_id(.,"train")), 
    data_ts = map(.x= data_ts, ~add_id(.,"test"))) %>%
  mutate(
      data = map2(.x = data_tr, .y = data_ts, ~bind_rows(.x,.y))) %>% 
  unnest(data) %>% #binding rows and unnesting the data
  select(-data_tr, -data_ts)
 
final_data
#reverting to longer format through pivoting 
final_data = final_data %>%
  select(division, date, starts_with("pred_freq"), id) %>%
  pivot_longer(starts_with("pred_freq"), names_to = "pango_lineage", values_to = "pred_freq") %>%
  mutate(pango_lineage = str_replace(pango_lineage,"^pred_freq_","")) %>%
  select(division, date, pango_lineage, pred_freq, id)


f_data = final_data %>%
  left_join(tidy_data) %>% 
  mutate(n = replace_na(n, 0)) %>% group_by(date, division) %>%
  mutate(sequence_total = sum(n)) %>% # Compute total sequences observed on that day in that place
  ungroup() %>%
  mutate(obs_freq = n / sequence_total) # Compute total frequency of lineage for each day and division

f_data
final_data
tidy_data










```




# Visualizing smoothed frequencies of train and test data


```{r}
final_data

plot1 = f_data %>% filter(division %in% c("Michigan", "New York", "Washington", "Colorado")) %>% 
  ggplot(aes(x=(as.Date(date)), y = obs_freq, color = pango_lineage)) + 
  geom_smooth(aes(y = obs_freq, shape = id), se = FALSE, size= 0.5) +
  geom_line(aes(y = pred_freq), linetype= "dashed") +
  facet_wrap(~division, strip.position = c("right")) +
  geom_vline(xintercept=as.numeric(as.Date("2021-03-05")), linetype=3, col = 'darkslategrey', size= 0.7) + annotate(geom="text",x=as.Date("2021-02-23"),
    y = 0.95, label=c("Train"), color = "darkslategrey", size = 4) +
  annotate(geom="text",x=as.Date("2021-03-15"),
    y = 0.95, label=c("Test"), color = "darkslategrey", size = 4) +
  labs(title = "", x = "", y = "Observed frequencies") + 
  theme_minimal() +
  theme(legend.title = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor  = element_blank(),
        axis.line = element_line(color = 'black'),
        plot.title = element_text(hjust = -0.45, vjust=2.12),
        axis.title.x=element_blank(),
        strip.text = element_text(size=10))

plot1


  
```













