---
title: "CV_test_tidy.rmd"
author: "Eslam Abousamra"
date: "7/21/2021"
output: html_document
---
```{r}
library(forecast)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(lubridate)
library(tidymodels)
library(rsample)
library(greybox)
library(caret)
library(yardstick)
```






```{r}

cv_data = read.csv("CV_long_df.csv") %>%
  select(-X) %>%
    mutate(date = as.Date(date)) %>%
  filter(division == "New York") %>%
  select(-division) %>% 
  arrange(date)

```


#Setting up the workflow
```{r}


multinomial_recipe = recipe(Pango.lineage ~ times, data = cv_data) %>%
    step_normalize(all_predictors()) #normalize standard dev and mean

multinomial_prep = prep(multinomial_recipe)


#
multinomial_spec = multinom_reg() %>%
  set_engine("nnet") #setting nnet package for multinom reg fit


multinomial_wf = workflow() %>%
  add_recipe(multinomial_recipe) %>%
  add_model(multinomial_spec)


#fit the data to the multinom workflow
fit_single_workflow = function(wf, data){
  # Fitting Single Model
  model_results = fit(wf, data)
}

#get prediction
get_single_preds = function(model, data){
  # Make sure all dates in range have predictions
  times <- seq(min(data$times), max(data$times))
  date <- times + min(data$date) - 1
  
  times_to_predict = data.frame(times = times, date = date)
  
  cbind(times_to_predict, predict(model, times_to_predict, type = "prob")) %>% # Combine data and model
    distinct(date, .keep_all = TRUE) %>% # Reduce to values by time
    pivot_longer(starts_with(".pred"), names_to = "Pango.lineage", values_to = "pred_freq") %>% # Pivot to tidy format
    mutate(Pango.lineage = str_replace(Pango.lineage,"^.pred_","")) # Fix pango_lineage
}

```


```{r}
#Spliting data on a sliding period

ts_split = sliding_period(cv_data, index = date, period = "day",
                          lookback = Inf,
                          assess_stop = 7,
                          skip = 2)




#Fit the splits and extract metrics

metrics = metric_set(mn_log_loss)

#Fitting the model
fold_test = multinomial_wf %>% 
  fit_resamples(ts_split, metrics = metrics, control = control_resamples(save_pred = TRUE))
  


#extracting metrics from the model
get_metric = function(split, predictions) {
  assessment = assessment(split)
  #Obt freqs
  assessment_freq = assessment %>%
    count(date, Pango.lineage) %>%
    group_by(date) %>%
    mutate(
    freq = n/sum(n)) %>%
    ungroup()
  #Getting predictions
  prediction = predictions %>%
  cbind(times = assessment$times,
        date = assessment$date) %>%
  distinct(times, .keep_all = TRUE) %>% 
  select(-Pango.lineage, -.row, -.config) %>%
  pivot_longer(starts_with(".pred_"), names_to = "Pango.lineage", values_to = "pred_freq") %>%
  mutate(Pango.lineage = str_replace(Pango.lineage,"^.pred_",""))
  #Joining test and train
  full_assessment = assessment_freq %>%
  left_join(prediction) %>% 
    replace_na(list(pred_freq = 0)) 
  #metrics
  full_assessment_summary = rmse(data= full_assessment, truth = freq, 
                           estimate = pred_freq)
  return(full_assessment_summary)
}

#extracting metric output
metric_output = fold_test %>%
  mutate(
    summary = map2(.x = splits, .y = .predictions, ~get_metric(.x, .y))
  ) 





```


```{r}

#Setting the variants appearance dates to variables
var_app = cv_data %>%
  group_by(Pango.lineage) %>%
  summarize(first_day = min(date))
#
var_diss = cv_data %>%
  group_by(Pango.lineage) %>%
  summarize(last_day = max(date))


#obtaining dates for variants appearance
get_f_data_set <- function(data, g){
  sum_data = data %>% summarize(g(date))
  sum_data[1,1]
}


#getting the output of the dates and merging them to the summarized metrics
metric_new = metric_output %>% 
  mutate(min_assess = map_dbl(splits, ~get_f_data_set(assessment(.), min)) %>%
           as_date(),
         max_assess = map_dbl(splits, ~get_f_data_set(assessment(.), max))%>%
           as_date() ,
         min_analysis = map_dbl(splits, ~get_f_data_set(analysis(.), min))%>%
           as_date(),
         max_analysis = map_dbl(splits, ~get_f_data_set(analysis(.), max))%>%
           as_date())


#Extracting the rsme values for plotting

extract_summary_metrics <- function(output){
   .estimate = output %>% 
      select(id, summary, min_assess, max_assess, min_analysis, max_analysis) %>%
    unnest(summary)
   return(.estimate)
}

#extracting the summaries and the dates of variants
summarydata = extract_summary_metrics(metric_new)

summarydata

```

#Plotting rolling cross-validation data and visualizing the rmse values

```{r}
cv_plot = summarydata %>% 
  ggplot(aes(x = min_assess, y = .estimate)) +
  geom_point(alpha = 1, shape = 19, size = 1, color = "forestgreen") +
    scale_color_viridis(discrete = TRUE, option = "D") +
  geom_vline(data = var_app, aes(xintercept = first_day, color = Pango.lineage), linetype= "dashed", size = 1) +
  theme_classic() +
  ylab("Root Mean Square Error") +
  xlab("Initial Test Prediction Date") +
  ggtitle("New York") 
cv_plot

ggsave("../cv_data_ny.png", plot = cv_plot, width = 7, height = 5)


```
#Plotting splits
```{r}

extract_dates_rsplit <- function(ts_split, date_col_name = "date"){
  an_obj <- rsample::analysis(ts_split)
  as_obj <- rsample::assessment(ts_split)
  
  tibble(analysis_min = min(an_obj[[date_col_name]]),
         analysis_max = max(an_obj[[date_col_name]]),
         assessment_min = min(as_obj[[date_col_name]]),
         assessment_max = max(as_obj[[date_col_name]])
  )
}



extract_dates_rset <- function(ts_split, date_col_name = "date"){
  ts_split %>% 
    mutate(dates = map(splits, extract_dates_rsplit, date_col_name = date_col_name)) %>% 
    unnest(dates)
}

plot_dates_rset <- function(ts_split){

  ts_split %>% 
    select(-one_of("splits")) %>%
    pivot_longer(cols = where(is.Date),
                 names_to = "type",
                 values_to = "date") %>% 
    separate(type, c("data_type", "range_type"), "_") %>% 
    ggplot(aes(y = fct_rev(id), x = date, colour = fct_rev(data_type)))+
    geom_line(size = 2)+
    scale_color_discrete(labels=c("Test","Train")) +
    scale_color_viridis(discrete = TRUE, option = "D") +
    theme_classic()+ 
    theme(legend.title = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        strip.background =element_blank())
}



#Extracting dates
splits_vis= ts_split %>% 
  extract_dates_rset()
#Plotting dates
splits_vis %>% 
  plot_dates_rset() 

#Subsetting for clearer visualization
cv_plot1 = splits_vis[c(1:30),]%>% 
  plot_dates_rset() 

cv_plot1 
cv_plot2 = splits_vis[c(60:90),] %>% 
  plot_dates_rset() 

ggsave("../slid_cv_1_.png", plot = cv_plot1, width = 7, height = 5)
ggsave("../slid_cv_2.png", plot = cv_plot2, width = 7, height = 5)


```
#Aggregate plot

```{r}



head(summarydata)



cv_plot = summarydata %>% 
  ggplot(aes(x = min_assess, y = .estimate)) +
  geom_point(alpha = 1, shape = 19, size = 1, color = "darkblue") +
       scale_color_manual(values=c("#4F34D2","#5299e0","#83cd93","#b5d765","#dadfe2",
"#ff5a30"))  +
  geom_vline(data = var_app, aes(xintercept = first_day, color = Pango.lineage), linetype= "dashed", size = 1) +
  theme_classic() +
  theme(legend.position = "none",
        strip.text = element_text(size=15)) +
  ylab("Root Mean Square Error") +
  xlab("Initial Test Prediction Date") +
  ggtitle("New York") 
cv_plot




plot_dates_rset <- function(ts_split){
  ts_split %>% 
    select(-one_of("splits")) %>%
    pivot_longer(cols = where(is.Date),
                 names_to = "type",
                 values_to = "date") %>% 
    separate(type, c("data_type", "range_type"), "_") %>% 
    ggplot(aes(y = fct_rev(id), x = date, colour = fct_rev(data_type)))+
    geom_line(size = 2)+
        scale_color_manual(values=c("#4F34D2","#5299e0","#83cd93","#b5d765","#dadfe2",
"#ff5a30"))+
    theme_classic()+ 
    #ylab("Date") +
    theme(legend.title = element_blank(),
          legend.position = "top",
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        strip.background =element_blank(),
        strip.text = element_text(size=15))
}

cv_plot1 = splits_vis[c(1:30),]%>% 
  plot_dates_rset() 
cv_plot1

library(ggpubr)

arranged_cv = ggarrange(cv_plot1, cv_plot, 
          #ncol = 1, nrow = 3,
          align = "hv",
          vjust = -1.5)
arranged_cv

ggsave("../arranged_cv1.png", plot = arranged_cv, width = 3000,
  height = 1200, units= ("px"))

```







